In [78]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [79]:
df = pd.read_csv("deep_insurance.txt")
df.head()

   age  affordability  bought_insurance
0   22           0.63                 0
1   25           0.81                 0
2   47           0.35                 1
3   52           0.42                 0
4   46           0.78                 1

In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['age','affordability']],df.bought_insurance,test_size = 0.2,random_state = 25)

In [81]:
len(x_train)

24

In [82]:
len(x_test)

6

In [83]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100 # Because the age is between 1 to 100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [84]:
x_train_scaled

     age  affordability
10  0.18           0.91
14  0.49           0.68
0   0.22           0.63
6   0.55           0.77
25  0.54           0.66
13  0.29           0.51
21  0.26           0.98
16  0.25           0.45
17  0.58           0.71
28  0.35           0.80
3   0.52           0.42
7   0.60           0.48
1   0.25           0.81
5   0.56           0.55
20  0.21           0.25
29  0.38           0.44
8   0.62           0.31
18  0.19           0.38
12  0.27           0.62
23  0.45           0.82
22  0.40           0.61
15  0.55           0.85
26  0.23           0.55
4   0.46           0.78

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,),activation = 'sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_scaled,y_train,epochs = 5000)

Epoch 1/5000

C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - accuracy: 0.5000 - loss: 0.7398
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7391
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7387
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7383
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7379
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7375
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7371
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7367
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7363
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7359
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7355
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7352
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7348
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7344
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7340
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7336
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7333
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7329
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7325
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7321
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7317
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7314
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7310
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7306
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7302
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7299
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7295
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7291
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7288
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7284
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7280
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7277
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7273
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7269
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7266
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7262
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7259
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7255
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7251
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7248
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7244
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7241
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7237
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7234
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7230
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7227
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7223
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7220
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7216
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7213
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7209
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7206
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7203
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7199
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7196
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7192
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7189
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7186
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7182
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7179
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7176
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7172
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7169
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7166
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7163
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7159
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7156
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7153
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7150
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7146
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7143
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7140
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7137
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7134
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7130
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7127
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7124
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7121
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7118
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7115
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7112
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7108
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7105
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7099
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7096
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7093
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7090
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7084
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7081
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7078
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7075
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7069
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7066
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7063
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7060
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7055
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7052
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7049
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7040
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7037
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7029
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7026
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7023
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7018
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7015
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7012
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7004
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7001
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6999
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6991
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6988
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6985
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6983
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6980
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6977
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6970
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6967
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6959
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6957
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6954
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6949
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6947
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6944
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6939
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6937
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6934
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6930
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6927
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6920
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6917
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6913
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6910
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6908
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6903
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6901
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6894
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6892
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6889
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6887
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6885
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6878
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6876
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6869
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6867
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6863
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6860
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6858
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6854
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6852
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6850
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6848
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6845
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6841
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6839
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6837
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6833
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6831
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6827
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6825
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6821
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6819
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6815
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6813
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6809
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6807
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6801
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6799
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6795
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6793
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6789
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6787
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6785
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6782
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6778
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6776
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6774
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6770
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6767
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6765
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6763
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6759
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 232/5000

In [88]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.4209

[0.42090216279029846, 1.0]

In [89]:
x_test_scaled

     age  affordability
19  0.18           0.52
11  0.28           0.85
2   0.47           0.35
9   0.61           0.59
24  0.50           0.74
27  0.30           0.69

In [90]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

array([[0.21790537],
       [0.42473283],
       [0.5477929 ],
       [0.78396225],
       [0.69727963],
       [0.40600935]], dtype=float32)

In [91]:
y_test

19    0
11    0
2     1
9     1
24    1
27    0
Name: bought_insurance, dtype: int64

In [92]:
coef,intercept = model.get_weights()
coef,intercept

(array([[5.773413 ],
        [1.2036334]], dtype=float32),
 array([-2.9430184], dtype=float32))

In [93]:
def sigmoid(x):
    import math
    return 1 / (1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [94]:
def prediction_function(age,affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability + intercept
    return sigmoid(weighted_sum)

In [95]:
prediction_function(.47,1)

C:\Users\avraj\AppData\Local\Temp\ipykernel_31784\3479825010.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1+math.exp(-x))

0.7259397772021446

In [96]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [max(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [97]:
def sigmoid_numpy(x):
    return 1 / (1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [98]:
def gradient_descent(age,affordability,y_true,epochs,loss_thresold):
    #w1 , w2 , bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true,y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)

        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print(f"Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}")

        if loss<=loss_thresold:
            break

    return w1 , w2 , bias

In [76]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordability'],y_train,1000, 0.7057)

Epoch:0,w1:0.9827073852295546,w2:0.9353476926419264,bias:-0.1157660021747731,loss:17.26978799617044
Epoch:1,w1:0.9716852097840707,w2:0.8808509795010323,bias:-0.21526056940632476,loss:17.26978799617044
Epoch:2,w1:0.96631501973388,w2:0.8355310703170917,bias:-0.30011922076900693,loss:17.26978799617044
Epoch:3,w1:0.965890424139119,w2:0.7982609776501282,bias:-0.37218523240887347,loss:17.26978799617044
Epoch:4,w1:0.9696956259125107,w2:0.7678938923907432,bias:-0.4333110910950285,loss:17.26978799617044
Epoch:5,w1:0.977056973620723,w2:0.7433479245018444,bias:-0.48523034469925097,loss:17.26978799617044
Epoch:6,w1:0.9873703699911953,w2:0.7236514956939896,bias:-0.529491134507635,loss:17.26978799617044
Epoch:7,w1:1.0001113291122454,w2:0.7079603353547339,bias:-0.5674333969275329,loss:17.26978799617044
Epoch:8,w1:1.014834360124366,w2:0.695556951470247,bias:-0.6001925365502376,loss:17.26978799617044
Epoch:9,w1:1.0311666976991605,w2:0.6858407819855592,bias:-0.6287168472047892,loss:17.26978799617044
Epoch:10,w1:1.048799630890358,w2:0.6783143529828223,bias:-0.6537905442794769,loss:17.26978799617044
Epoch:11,w1:1.0674793191009277,w2:0.6725685430612149,bias:-0.6760577430949825,loss:17.26978799617044
Epoch:12,w1:1.0869980815942928,w2:0.6682685762169944,bias:-0.6960449883525277,loss:17.26978799617044
Epoch:13,w1:1.1071866034045303,w2:0.6651414748020167,bias:-0.7141812924277561,loss:17.26978799617044
Epoch:14,w1:1.1279071963693872,w2:0.6629652053781149,bias:-0.7308153882133055,loss:17.26978799617044
Epoch:15,w1:1.1490480963589262,w2:0.661559491463472,bias:-0.7462302838584435,loss:17.26978799617044
Epoch:16,w1:1.1705187045463195,w2:0.6607781466749708,bias:-0.7606553793462008,loss:17.26978799617044
Epoch:17,w1:1.1922456536037265,w2:0.660502737091815,bias:-0.7742764641523486,loss:17.26978799617044
Epoch:18,w1:1.214169576716898,w2:0.6606373762868598,bias:-0.7872439166901967,loss:17.26978799617044
Epoch:19,w1:1.236242465767747,w2:0.6611044698708016,bias:-0.7996794007458983,loss:17.26978799617044
Epoch:20,w1:1.2584255181339552,w2:0.6618412474348326,bias:-0.8116813182367968,loss:17.26978799617044
Epoch:21,w1:1.2806873857572572,w2:0.6627969426623119,bias:-0.823329239895693,loss:17.26978799617044
Epoch:22,w1:1.3030027537047035,w2:0.6639305042734281,bias:-0.8346874999718681,loss:17.26978799617044
Epoch:23,w1:1.325351187636737,w2:0.665208740135245,bias:-0.8458081094408617,loss:17.26978799617044
Epoch:24,w1:1.3477162001633105,w2:0.6666048139200349,bias:-0.856733114992828,loss:17.26978799617044
Epoch:25,w1:1.370084495032897,w2:0.6680970281549391,bias:-0.8674965080831215,loss:17.26978799617044
Epoch:26,w1:1.3924453555954701,w2:0.6696678395958445,bias:-0.8781257691711007,loss:17.26978799617044
Epoch:27,w1:1.4147901501898634,w2:0.6713030628699403,bias:-0.888643116446151,loss:17.26978799617044
Epoch:28,w1:1.4371119322151769,w2:0.6729912265670396,bias:-0.8990665153439307,loss:17.26978799617044
Epoch:29,w1:1.4594051168301323,w2:0.6747230527026019,bias:-0.9094104945303183,loss:17.26978799617044
Epoch:30,w1:1.481665219639244,w2:0.6764910359772991,bias:-0.9196868053700048,loss:17.26978799617044
Epoch:31,w1:1.5038886455047589,w2:0.6782891037361056,bias:-0.9299049548537427,loss:17.26978799617044
Epoch:32,w1:1.5260725178823094,w2:0.6801123411680264,bias:-0.9400726362404063,loss:17.26978799617044
Epoch:33,w1:1.54821454091117,w2:0.681956769239134,bias:-0.9501960770337616,loss:17.26978799617044
Epoch:34,w1:1.570312887975669,w2:0.6838191652436291,bias:-0.9602803201581641,loss:17.26978799617044
Epoch:35,w1:1.5923661116574652,w2:0.6856969177946627,bias:-0.9703294511572311,loss:17.26978799617044
Epoch:36,w1:1.6143730709721775,w2:0.6875879096442499,bias:-0.9803467817799185,loss:17.26978799617044
Epoch:37,w1:1.636332872571558,w2:0.689490422989635,bias:-0.9903349983293328,loss:17.26978799617044
Epoch:38,w1:1.6582448232293907,w2:0.6914030629487983,bias:-1.0002962815415428,loss:17.26978799617044
Epoch:39,w1:1.680108391444213,w2:0.6933246957166529,bias:-1.0102324034619357,loss:17.26978799617044
Epoch:40,w1:1.7019231764081384,w2:0.6952543985833807,bias:-1.0201448057363636,loss:17.26978799617044
Epoch:41,w1:1.7236888829273591,w2:0.6971914195376859,bias:-1.0300346628856973,loss:17.26978799617044
Epoch:42,w1:1.7454053011516293,w2:0.6991351446151434,bias:-1.0399029334467769,loss:17.26978799617044
Epoch:43,w1:1.7670722901895652,w2:0.7010850715052012,bias:-1.0497504013088714,loss:17.26978799617044
Epoch:44,w1:1.7886897648639442,w2:0.7030407882158941,bias:-1.059577709127314,loss:17.26978799617044
Epoch:45,w1:1.8102576850044498,w2:0.7050019558259633,bias:-1.069385385334535,loss:17.26978799617044
Epoch:46,w1:1.8317760467910507,w2:0.7069682945403996,bias:-1.079173865976739,loss:17.26978799617044
Epoch:47,w1:1.8532448757546847,w2:0.7089395724159508,bias:-1.088943512368612,loss:17.26978799617044
Epoch:48,w1:1.8746642211174462,w2:0.7109155962447311,bias:-1.0986946253679126,loss:17.26978799617044
Epoch:49,w1:1.8960341512154861,w2:0.7128962041823069,bias:-1.1084274569178836,loss:17.26978799617044
Epoch:50,w1:1.9173547497971162,w2:0.7148812597860055,bias:-1.118142219381071,loss:17.26978799617044
Epoch:51,w1:1.9386261130284341,w2:0.7168706471933072,bias:-1.1278390930876843,loss:17.26978799617044
Epoch:52,w1:1.9598483470709502,w2:0.7188642672219976,bias:-1.137518232440459,loss:17.26978799617044
Epoch:53,w1:1.98102156612169,w2:0.7208620342156142,bias:-1.1471797708524143,loss:17.26978799617044
Epoch:54,w1:2.0021458908272485,w2:0.7228638734915488,bias:-1.156823824740905,loss:17.26978799617044
Epoch:55,w1:2.0232214470002403,w2:0.7248697192765013,bias:-1.166450496758547,loss:17.26978799617044
Epoch:56,w1:2.044248364580302,w2:0.7268795130360717,bias:-1.176059878407001,loss:17.26978799617044
Epoch:57,w1:2.0652267767928865,w2:0.7288932021231274,bias:-1.1856520521516332,loss:17.26978799617044
Epoch:58,w1:2.086156819468043,w2:0.7309107386840148,bias:-1.1952270931324678,loss:17.26978799617044
Epoch:59,w1:2.107038630488616,w2:0.7329320787733448,bias:-1.2047850705485876,loss:17.26978799617044
Epoch:60,w1:2.127872349343146,w2:0.7349571816375106,bias:-1.2143260487783665,loss:17.26978799617044
Epoch:61,w1:2.1486581167634844,w2:0.7369860091347182,bias:-1.2238500882859873,loss:17.26978799617044
Epoch:62,w1:2.1693960744309604,w2:0.739018525265469,bias:-1.233357246355046,loss:17.26978799617044
Epoch:63,w1:2.1900863647380255,w2:0.7410546957924176,bias:-1.2428475776822434,loss:17.26978799617044
Epoch:64,w1:2.2107291305947996,w2:0.7430944879325556,bias:-1.2523211348578605,loss:17.26978799617044
Epoch:65,w1:2.231324515271966,w2:0.7451378701079281,bias:-1.2617779687546071,loss:17.26978799617044
Epoch:66,w1:2.2518726622730982,w2:0.747184811743724,bias:-1.2712181288423179,loss:17.26978799617044
Epoch:67,w1:2.272373715230816,w2:0.7492352831047131,bias:-1.2806416634426248,loss:17.26978799617044
Epoch:68,w1:2.29282781782224,w2:0.7512892551627233,bias:-1.290048619935046,loss:17.26978799617044
Epoch:69,w1:2.313235113700087,w2:0.7533466994892466,bias:-1.2994390449237434,loss:17.26978799617044
Epoch:70,w1:2.333595746436426,w2:0.75540758816839,bias:-1.3088129843724376,loss:17.26978799617044
Epoch:71,w1:2.3539098594767105,w2:0.7574718937262982,bias:-1.318170483713544,loss:17.26978799617044
Epoch:72,w1:2.374177596102128,w2:0.7595395890739142,bias:-1.3275115879364328,loss:17.26978799617044
Epoch:73,w1:2.394399099398705,w2:0.761610647460541,bias:-1.3368363416587867,loss:17.26978799617044
Epoch:74,w1:2.414574512231887,w2:0.7636850424361493,bias:-1.3461447891842708,loss:17.26978799617044
Epoch:75,w1:2.434703977225565,w2:0.7657627478207694,bias:-1.355436974549116,loss:17.26978799617044
Epoch:76,w1:2.454787636744715,w2:0.7678437376796188,bias:-1.3647129415597263,loss:17.26978799617044
Epoch:77,w1:2.4748256328809677,w2:0.7699279863028781,bias:-1.3739727338230139,loss:17.26978799617044
Epoch:78,w1:2.494818107440572,w2:0.7720154681892285,bias:-1.383216394770846,loss:17.26978799617044
Epoch:79,w1:2.5147652019342943,w2:0.7741061580324391,bias:-1.3924439676797216,loss:17.26978799617044
Epoch:80,w1:2.5346670575689063,w2:0.7762000307104215,bias:-1.4016554956865857,loss:17.26978799617044
Epoch:81,w1:2.5545238152399627,w2:0.7782970612762856,bias:-1.4108510218015153,loss:17.26978799617044
Epoch:82,w1:2.5743356155256363,w2:0.7803972249510135,bias:-1.420030588917872,loss:17.26978799617044
Epoch:83,w1:2.594102598681416,w2:0.7825004971174458,bias:-1.429194239820402,loss:17.26978799617044
Epoch:84,w1:2.6138249046355164,w2:0.7846068533153301,bias:-1.4383420171916772,loss:17.26978799617044
Epoch:85,w1:2.633502672984869,w2:0.7867162692372277,bias:-1.4474739636171905,loss:17.26978799617044
Epoch:86,w1:2.6531360429915964,w2:0.7888287207251182,bias:-1.4565901215893644,loss:17.26978799617044
Epoch:87,w1:2.6727251535798824,w2:0.7909441837675658,bias:-1.4656905335106796,loss:17.26978799617044
Epoch:88,w1:2.6922701433331757,w2:0.7930626344973419,bias:-1.4747752416960913,loss:17.26978799617044
Epoch:89,w1:2.711771150491671,w2:0.795184049189416,bias:-1.4838442883748721,loss:17.26978799617044
Epoch:90,w1:2.7312283129500172,w2:0.7973084042592437,bias:-1.4928977156919903,loss:17.26978799617044
Epoch:91,w1:2.7506417682552287,w2:0.7994356762612961,bias:-1.5019355657091131,loss:17.26978799617044
Epoch:92,w1:2.7700116536047563,w2:0.8015658418877822,bias:-1.5109578804053105,loss:17.26978799617044
Epoch:93,w1:2.7893381058447075,w2:0.8036988779675287,bias:-1.519964701677514,loss:17.26978799617044
Epoch:94,w1:2.8086212614681836,w2:0.8058347614649846,bias:-1.5289560713407826,loss:17.26978799617044
Epoch:95,w1:2.827861256613729,w2:0.8079734694793276,bias:-1.5379320311284126,loss:17.26978799617044
Epoch:96,w1:2.847058227063872,w2:0.8101149792436522,bias:-1.546892622691922,loss:17.26978799617044
Epoch:97,w1:2.8662123082437496,w2:0.8122592681242219,bias:-1.5558378876009378,loss:17.26978799617044
Epoch:98,w1:2.8853236352198097,w2:0.8144063136197739,bias:-1.5647678673430028,loss:17.26978799617044
Epoch:99,w1:2.9043923426985763,w2:0.8165560933608645,bias:-1.573682603323323,loss:17.26978799617044
Epoch:100,w1:2.92341856502548,w2:0.8187085851092483,bias:-1.5825821368644664,loss:17.26978799617044
Epoch:101,w1:2.9424024361837455,w2:0.8208637667572813,bias:-1.5914665092060232,loss:17.26978799617044
Epoch:102,w1:2.9613440897933287,w2:0.8230216163273465,bias:-1.6003357615042413,loss:17.26978799617044
Epoch:103,w1:2.9802436591099064,w2:0.8251821119712928,bias:-1.6091899348316385,loss:17.26978799617044
Epoch:104,w1:2.9991012770239105,w2:0.8273452319698875,bias:-1.6180290701766005,loss:17.26978799617044
Epoch:105,w1:3.017917076059608,w2:0.8295109547322773,bias:-1.6268532084429688,loss:17.26978799617044
Epoch:106,w1:3.036691188374222,w2:0.8316792587954555,bias:-1.6356623904496226,loss:17.26978799617044
Epoch:107,w1:3.0554237457570914,w2:0.8338501228237345,bias:-1.6444566569300563,loss:17.26978799617044
Epoch:108,w1:3.074114879628874,w2:0.8360235256082219,bias:-1.6532360485319573,loss:17.26978799617044
Epoch:109,w1:3.092764721040782,w2:0.8381994460662978,bias:-1.6620006058167844,loss:17.26978799617044
Epoch:110,w1:3.1113734006738576,w2:0.8403778632410936,bias:-1.670750369259349,loss:17.26978799617044
Epoch:111,w1:3.129941048838281,w2:0.8425587563009715,bias:-1.679485379247401,loss:17.26978799617044
Epoch:112,w1:3.1484677954727163,w2:0.8447421045390032,bias:-1.6882056760812183,loss:17.26978799617044
Epoch:113,w1:3.1669537701436865,w2:0.8469278873724484,bias:-1.6969112999732043,loss:17.26978799617044
Epoch:114,w1:3.1853991020449857,w2:0.8491160843422321,bias:-1.7056022910474906,loss:17.26978799617044
Epoch:115,w1:3.203803919997121,w2:0.8513066751124203,bias:-1.7142786893395465,loss:17.26978799617044
Epoch:116,w1:3.222168352446787,w2:0.853499639469695,bias:-1.7229405347957973,loss:17.26978799617044
Epoch:117,w1:3.240492527466369,w2:0.8556949573228266,bias:-1.7315878672732488,loss:17.26978799617044
Epoch:118,w1:3.258776572753481,w2:0.8578926087021458,bias:-1.7402207265391207,loss:17.26978799617044
Epoch:119,w1:3.277020615630529,w2:0.8600925737590124,bias:-1.748839152270489,loss:17.26978799617044
Epoch:120,w1:3.2952247830443047,w2:0.8622948327652837,bias:-1.757443184053934,loss:17.26978799617044
Epoch:121,w1:3.31338920156561,w2:0.8644993661127801,bias:-1.7660328613851999,loss:17.26978799617044
Epoch:122,w1:3.3315139973889076,w2:0.8667061543127494,bias:-1.77460822366886,loss:17.26978799617044
Epoch:123,w1:3.3495992963320016,w2:0.8689151779953298,bias:-1.7831693102179924,loss:17.26978799617044
Epoch:124,w1:3.367645223835742,w2:0.8711264179090101,bias:-1.7917161602538623,loss:17.26978799617044
Epoch:125,w1:3.3856519049637597,w2:0.8733398549200899,bias:-1.8002488129056142,loss:17.26978799617044
Epoch:126,w1:3.4036194644022264,w2:0.8755554700121368,bias:-1.8087673072099721,loss:17.26978799617044
Epoch:127,w1:3.4215480264596403,w2:0.8777732442854431,bias:-1.8172716821109474,loss:17.26978799617044
Epoch:128,w1:3.439437715066638,w2:0.8799931589564807,bias:-1.825761976459555,loss:17.26978799617044
Epoch:129,w1:3.4572886537758327,w2:0.8822151953573548,bias:-1.8342382290135386,loss:17.26978799617044
Epoch:130,w1:3.4751009657616736,w2:0.884439334935257,bias:-1.8427004784371035,loss:17.26978799617044
Epoch:131,w1:3.4928747738203345,w2:0.8866655592519156,bias:-1.8511487633006571,loss:17.26978799617044
Epoch:132,w1:3.510610200369624,w2:0.888893849983047,bias:-1.859583122080558,loss:17.26978799617044
Epoch:133,w1:3.5283073674489183,w2:0.8911241889178043,bias:-1.868003593158873,loss:17.26978799617044
Epoch:134,w1:3.54596639671912,w2:0.8933565579582264,bias:-1.876410214823141,loss:17.26978799617044
Epoch:135,w1:3.563587409462638,w2:0.8955909391186854,bias:-1.8848030252661458,loss:17.26978799617044
Epoch:136,w1:3.5811705265833895,w2:0.8978273145253333,bias:-1.8931820625856963,loss:17.26978799617044
Epoch:137,w1:3.5987158686068264,w2:0.9000656664155489,bias:-1.9015473647844134,loss:17.26978799617044
Epoch:138,w1:3.616223555679981,w2:0.9023059771373831,bias:-1.9098989697695257,loss:17.26978799617044
Epoch:139,w1:3.633693707571535,w2:0.9045482291490049,bias:-1.918236915352671,loss:17.26978799617044
Epoch:140,w1:3.65112644367191,w2:0.9067924050181453,bias:-1.9265612392497076,loss:17.26978799617044
Epoch:141,w1:3.668521882993375,w2:0.9090384874215427,bias:-1.9348719790805295,loss:17.26978799617044
Epoch:142,w1:3.6858801441701794,w2:0.9112864591443869,bias:-1.943169172368892,loss:17.26978799617044
Epoch:143,w1:3.7032013454587025,w2:0.9135363030797632,bias:-1.9514528565422418,loss:17.26978799617044
Epoch:144,w1:3.720485604737624,w2:0.9157880022280966,bias:-1.959723068931556,loss:17.26978799617044
Epoch:145,w1:3.737733039508115,w2:0.9180415396965961,bias:-1.9679798467711862,loss:17.26978799617044
Epoch:146,w1:3.7549437668940446,w2:0.9202968986986979,bias:-1.976223227198712,loss:17.26978799617044
Epoch:147,w1:3.7721179036422106,w2:0.9225540625535107,bias:-1.9844532472547975,loss:17.26978799617044
Epoch:148,w1:3.789255566122582,w2:0.9248130146852591,bias:-1.9926699438830582,loss:17.26978799617044
Epoch:149,w1:3.806356870328566,w2:0.9270737386227288,bias:-2.000873353929932,loss:17.26978799617044
Epoch:150,w1:3.8234219318772897,w2:0.929336217998711,bias:-2.0090635141445574,loss:17.26978799617044
Epoch:151,w1:3.840450866009897,w2:0.9316004365494482,bias:-2.0172404611786585,loss:17.26978799617044
Epoch:152,w1:3.8574437875918677,w2:0.9338663781140795,bias:-2.0254042315864362,loss:17.26978799617044
Epoch:153,w1:3.8744008111133503,w2:0.9361340266340868,bias:-2.0335548618244648,loss:17.26978799617044
Epoch:154,w1:3.891322050689512,w2:0.938403366152742,bias:-2.041692388251595,loss:17.26978799617044
Epoch:155,w1:3.9082076200609035,w2:0.9406743808145535,bias:-2.049816847128865,loss:17.26978799617044
Epoch:156,w1:3.9250576325938447,w2:0.9429470548647148,bias:-2.057928274619414,loss:17.26978799617044
Epoch:157,w1:3.9418722012808187,w2:0.945221372648553,bias:-2.066026706788404,loss:17.26978799617044
Epoch:158,w1:3.9586514387408873,w2:0.9474973186109785,bias:-2.0741121796029485,loss:17.26978799617044
Epoch:159,w1:3.9753954572201198,w2:0.949774877295935,bias:-2.0821847289320425,loss:17.26978799617044
Epoch:160,w1:3.9921043685920345,w2:0.9520540333458506,bias:-2.090244390546504,loss:17.26978799617044
Epoch:161,w1:4.0087782843580575,w2:0.9543347715010903,bias:-2.098291200118916,loss:17.26978799617044
Epoch:162,w1:4.025417315647996,w2:0.9566170765994085,bias:-2.106325193223578,loss:17.26978799617044
Epoch:163,w1:4.042021573220522,w2:0.9589009335754038,bias:-2.11434640533646,loss:17.26978799617044
Epoch:164,w1:4.058591167463673,w2:0.9611863274599735,bias:-2.122354871835163,loss:17.26978799617044
Epoch:165,w1:4.075126208395367,w2:0.9634732433797698,bias:-2.1303506279988853,loss:17.26978799617044
Epoch:166,w1:4.0916268056639264,w2:0.9657616665566577,bias:-2.138333709008394,loss:17.26978799617044
Epoch:167,w1:4.108093068548621,w2:0.9680515823071734,bias:-2.1463041499460003,loss:17.26978799617044
Epoch:168,w1:4.124525105960216,w2:0.9703429760419836,bias:-2.1542619857955416,loss:17.26978799617044
Epoch:169,w1:4.1409230264415395,w2:0.9726358332653475,bias:-2.162207251442367,loss:17.26978799617044
Epoch:170,w1:4.15728693816806,w2:0.9749301395745786,bias:-2.1701399816733287,loss:17.26978799617044
Epoch:171,w1:4.173616948948472,w2:0.9772258806595083,bias:-2.17806021117678,loss:17.26978799617044
Epoch:172,w1:4.189913166225301,w2:0.9795230423019515,bias:-2.185967974542574,loss:17.26978799617044
Epoch:173,w1:4.206175697075512,w2:0.9818216103751731,bias:-2.19386330626207,loss:17.26978799617044
Epoch:174,w1:4.2224046482111355,w2:0.9841215708433558,bias:-2.201746240728144,loss:17.26978799617044
Epoch:175,w1:4.238600125979899,w2:0.9864229097610697,bias:-2.209616812235205,loss:17.26978799617044
Epoch:176,w1:4.254762236365877,w2:0.9887256132727436,bias:-2.2174750549792117,loss:17.26978799617044
Epoch:177,w1:4.27089108499014,w2:0.9910296676121371,bias:-2.225321003057699,loss:17.26978799617044
Epoch:178,w1:4.286986777111429,w2:0.9933350591018154,bias:-2.2331546904698047,loss:17.26978799617044
Epoch:179,w1:4.303049417626824,w2:0.9956417741526247,bias:-2.2409761511163038,loss:17.26978799617044
Epoch:180,w1:4.319079111072435,w2:0.9979497992631698,bias:-2.2487854187996446,loss:17.26978799617044
Epoch:181,w1:4.335075961624097,w2:1.0002591210192935,bias:-2.256582527223989,loss:17.26978799617044
Epoch:182,w1:4.351040073098073,w2:1.0025697260935569,bias:-2.2643675099952607,loss:17.26978799617044
Epoch:183,w1:4.366971548951772,w2:1.0048816012447224,bias:-2.2721404006211916,loss:17.26978799617044
Epoch:184,w1:4.382870492284474,w2:1.007194733317238,bias:-2.2799012325113766,loss:17.26978799617044
Epoch:185,w1:4.398737005838056,w2:1.0095091092407236,bias:-2.287650038977331,loss:17.26978799617044
Epoch:186,w1:4.41457119199774,w2:1.0118247160294587,bias:-2.2953868532325514,loss:17.26978799617044
Epoch:187,w1:4.430373152792841,w2:1.014141540781872,bias:-2.3031117083925827,loss:17.26978799617044
Epoch:188,w1:4.446142989897522,w2:1.0164595706800332,bias:-2.3108246374750845,loss:17.26978799617044
Epoch:189,w1:4.461880804631566,w2:1.0187787929891472,bias:-2.318525673399905,loss:17.26978799617044
Epoch:190,w1:4.4775866979611445,w2:1.0210991950570483,bias:-2.326214848989157,loss:17.26978799617044
Epoch:191,w1:4.493260770499603,w2:1.0234207643136983,bias:-2.3338921969672985,loss:17.26978799617044
Epoch:192,w1:4.508903122508249,w2:1.0257434882706857,bias:-2.3415577499612157,loss:17.26978799617044
Epoch:193,w1:4.524513853897149,w2:1.0280673545207264,bias:-2.3492115405003102,loss:17.26978799617044
Epoch:194,w1:4.540093064225933,w2:1.0303923507371677,bias:-2.356853601016589,loss:17.26978799617044
Epoch:195,w1:4.555640852704602,w2:1.0327184646734928,bias:-2.3644839638447586,loss:17.26978799617044
Epoch:196,w1:4.571157318194353,w2:1.0350456841628286,bias:-2.3721026612223217,loss:17.26978799617044
Epoch:197,w1:4.5866425592083955,w2:1.037373997117454,bias:-2.3797097252896786,loss:17.26978799617044
Epoch:198,w1:4.602096673912787,w2:1.0397033915283125,bias:-2.38730518809023,loss:17.26978799617044

(np.float64(11.664677572607788),
 np.float64(2.845622893641206),
 np.float64(-6.350104999512562))

In [99]:
coef,intercept

(array([[5.773413 ],
        [1.2036334]], dtype=float32),
 array([-2.9430184], dtype=float32))

In [ ]:
w1 = 5.06087 , w2 = 1.4086502 , bias = -2.9137027